services:
  fcp-jkr-demo-backend-node:
    build:
      context: .
      target: production
    image: fcp-jkr-demo-backend-node
    container_name: fcp-jkr-demo-backend-node
    depends_on:
      - fcp-jkr-demo-backend-node-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-jkr-demo-backend-node-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

